name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and run PostgreSQL container
        run: docker-compose -f docker-compose.yml up --detach


      - name: Wait for PostgreSQL to start
        run: sleep 15

      - name: Build with Maven
        run: mvn -B clean install

      - name: Test application
        run: mvn -B test

      - name: Stop and remove PostgreSQL container
        run: docker-compose -f docker-compose.yml down
